In [1]:
import os

import numpy as np

import matplotlib.pyplot as plt

import tensorflow as tf

#### Data preprocessing

In [3]:
import tensorflow_datasets as tfds
tfds.disable_progress_bar()

ImportError: This version of TensorFlow Datasets requires TensorFlow version >= 1.15.0; Detected an installation of version 1.14.0. Please upgrade TensorFlow to proceed.

In [2]:
from sympy import *
import numpy as np


In [13]:
a = np.array([[1,1,2],
             [2,4,-3],
             [3,6,5]])
print(a)

[[ 1  1  2]
 [ 2  4 -3]
 [ 3  6  5]]


In [14]:
a1 = Matrix(a)
a1

Matrix([
[1, 1,  2],
[2, 4, -3],
[3, 6,  5]])

In [15]:
a1.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))